### PR TITLE
Front end layout

### PR DESCRIPTION
**Pull request by lsatkins**
finished nav and main layouts layouts

### CODE REVIEW

**Review by elehma4 — APPROVED** [review]
Front-End Framework

**Review by elehma4 — APPROVED** [review]
Front end layout

**Review by elehma4 — APPROVED** [review]

**Review by vlino2015 — COMMENTED** [review]
complete

**Review by vlino2015 — COMMENTED** [review]
complete

**Review by vlino2015 — COMMENTED** [review]
complete

**Review by vlino2015 — COMMENTED** [review]
sdf

**Review by vlino2015 — COMMENTED** [review]
sdfs

**Review by vlino2015 — COMMENTED** [review]
sdsdf

**Pull request closed without merging**
